ci/cd:
  - .github/*
  - scripts/*
  - .travis.yml
doc: ./**/README.md
docker:
  - .dockerignore
  - scripts/*
  - ./**/DOCKERFILE
edge-gateway: source/edge-gateway/**
federation:
  gateway: source/federation/apollo-federation-express-gateway/**
  movie-api: source/federation/federated-movie-api/**
  user-management: source/federation/federated-user-management/**
frontend:
  web-ui: source/frontend/next-js-web-ui/**
java: source/**/*.java
javascript: source/**/*.js
stream:
  upstream: source/stream/upstream-server/**
tooling:
  - ./**/.idea/*
  - ./**/.gitignore
  - gradle/*
  - gradle*
  - ./**/*.gradle
  - source/**/package*.json
