logging:
  level:
    root: debug
management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8090}
server:
  port: ${SERVER_PORT:8080}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
