auth0:
  audience: ${JWT_AUDIENCE}
management:
  endpoints:
    web:
      exposure:
        include: health, info
  server:
    port: ${MANAGEMENT_SERVER_PORT:8090}
server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: edge-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
