management:
  server:
    port: 8099
server:
  port: 8088
  servlet:
    context-path: /auth
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bbortt_tv_authorization
    username: bbortt_tv_authorization
    password: bbortt_tv_authorization
  redis:
    host: localhost
    port: 6379
