version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: ./gradlew assemble --no-daemon -i
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew check --no-daemon -i
    working_directory: ~/repo
