version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: ./gradlew --no-daemon -i assemble
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew -Pproject.version=$CIRCLE_BUILD_NUM --no-daemon -i check
    working_directory: ~/repo
