management:
  server:
    port: 8099
server:
  port: 8088
  servlet:
    context-path: /auth
spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/${spring.datasource.username}
    username: bbortt_tv_authorization
    password: ${spring.datasource.username}
  redis:
    host: localhost
    port: 6379
tokenstore:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/${tokenstore.datasource.username}
    username: bbortt_tv_tokenstore
    password: ${tokenstore.datasource.username}
