eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: true
zuul:
  routes:
    microservice:
      custom-sensitive-headers: true
      path: /microservice/**
      sensitive-headers:
      - Cookie
      - Set-Cookie
      serviceId: microservice
