name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Because of recent inactivity this issue will be marked as stale!'
        stale-pr-message: 'Because of recent inactivity this pull-request will be marked as stale!'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
